caching enabled status per logger
visionmedia/debug pull request #799
Opened 2020-12-08 22:24 UTC by omg

Can we have this to avoid rechecking rules on each call?

2020-12-09 13:34 UTC, Qix- commented
Please explain what this does. What problem are you facing?

2020-12-09 14:18 UTC, omg commented
Current implementation checks whether the namespace is enabled against the lists of regexes each time the debug instance is called. This change addresses this by caching the enabled flag in the debug instance to avoid reevaluating it each time. Since the library supports dynamically changing namespace configuration, the change also addresses this by caching reference to namespace config in the instance and comparing it against the current config (lazily). When the references are different the new config reference is replaces the previously cached one and the enabled flag reevaluated so nothing breaks but redundant regex checks are cut off.

2020-12-09 14:38 UTC, Qix- requested changes
Sounds good, thanks!

Just a few small nitpicks and I'll merge.

2020-12-09 14:38 UTC, Qix- commented on src/common.js
> +					return enableOverride
```suggestion
					return enableOverride;
```

2020-12-09 14:38 UTC, Qix- commented on src/common.js
> +
```suggestion

				return enabledCache;
```

2020-12-09 14:38 UTC, Qix- commented on src/common.js
> +		let namespacesCache, enabledCache;
```suggestion
		let namespacesCache;
		let enabledCache;
```

2020-12-09 15:34 UTC, merged

2020-12-09 15:36 UTC, Qix- commented
Released as `4.3.2` on the `beta` tag.

2021-01-08 13:56 UTC, diverdowngit commented
juuhhyggbb

2021-01-08 13:59 UTC, diverdowngit commented
2.6.9